In [22]:
from sympy import Matrix
from sympy.printing.latex import latex

from nablaDFT.dataset import HamiltonianDatabase

train = HamiltonianDatabase("train_2k.db.1")
# atoms numbers, atoms positions, energy, forces, core hamiltonian, overlap matrix, coefficients matrix,
# moses_id, conformation_id
Z, R, E, F, H, S, C, moses_id, conformation_id = train[0]

In [23]:
print(len(H), 'x', len(H[0]))
print('atoms numbers: ', Z)
print('atoms positions: ', R)

402 x 402
atoms numbers:  [6 6 7 6 6 7 6 8 6 7 6 6 6 8 7 6 6 6 6 6 6 7 7 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]
atoms positions:  [[12.381227   -1.6390955   0.99412256]
 [10.60808    -1.4759347  -1.264499  ]
 [ 8.206612   -0.30607894 -0.51739   ]
 [ 6.1327586  -1.4889795   0.35170072]
 [ 4.2733946   0.2647034   0.83938235]
 [ 1.7510334  -0.13743979  1.7892759 ]
 [ 0.1485835   1.9786887   2.1191106 ]
 [ 0.9965735   4.1259356   1.5764493 ]
 [-2.4638078   1.7212306   3.0714474 ]
 [-4.2715445   1.13479     1.1013815 ]
 [-5.605585    2.681132   -0.38528493]
 [-5.587442    5.418015   -0.36191657]
 [-7.1772933   6.826564   -2.175137  ]
 [-4.2307696   6.5596795   1.1861527 ]
 [-7.0589304   1.2952561  -1.9698147 ]
 [-6.67727    -1.1683024  -1.519217  ]
 [-7.718418   -3.2837431  -2.631555  ]
 [-6.963811   -5.617052   -1.7607826 ]
 [-5.2102337  -5.754165    0.17507556]
 [-4.201672   -3.6114821   1.2513143 ]
 [-4.9278784  -1.2431828   0.40959623]
 [ 5.313016    2.5302336   0.23101334]
 [ 7.6491995   2.

In [29]:
import ase
from ase.db import connect
from ase.units import Bohr
from ase.visualize import view
atom = ase.Atoms(Z, R * Bohr)
view(atom, viewer="x3d")

In [ ]:
import pennylane as qml
from pennylane import numpy as np
from pennylane import qchem 

In [30]:
symbols = ['C', 'C', 'N', 'C', 'C', 'N', 'C', 'O', 'C', 'N', 'C', 'C', 'C', 'O', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'N', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
coordinates = np.array(R)

In [35]:
hamiltonian, qubits = qchem.molecular_hamiltonian(symbols,coordinates, charge = 0, method= 'openfermion' )

UnboundLocalError: cannot access local variable 'geometry_hf' where it is not associated with a value

In [ ]:
print(hamiltonian)

-0.299750614501162 * I(0) + 0.21445495423161076 * Z(0) + -4.320173596344262e-07 * (Y(0) @ Z(1) @ Y(2)) + -4.320173596344262e-07 * (X(0) @ Z(1) @ X(2)) + 3.6614993002143104e-07 * (Y(0) @ Z(1) @ Z(2) @ Z(3) @ Y(4)) + 3.6614993002143104e-07 * (X(0) @ Z(1) @ Z(2) @ Z(3) @ X(4)) + -0.11489380123586872 * Z(2) + 0.1069610957870239 * (Z(0) @ Z(2)) + -0.11491204817793832 * Z(4) + 0.10696270053341995 * (Z(0) @ Z(4)) + 0.21445495423161084 * Z(1) + 0.1470311657923632 * (Z(0) @ Z(1)) + 1.1014771324068147e-06 * (Y(0) @ Y(2)) + 1.1014771324068147e-06 * (X(0) @ X(2)) + -9.333921850720149e-07 * (Y(0) @ Z(2) @ Z(3) @ Y(4)) + -9.333921850720149e-07 * (X(0) @ Z(2) @ Z(3) @ X(4)) + -4.320173596326915e-07 * (Y(1) @ Z(2) @ Y(3)) + 1.1014771324068147e-06 * (Z(0) @ Y(1) @ Z(2) @ Y(3)) + -4.320173596326915e-07 * (X(1) @ Z(2) @ X(3)) + 1.1014771324068147e-06 * (Z(0) @ X(1) @ Z(2) @ X(3)) + 0.03599964576765458 * (Y(0) @ X(1) @ X(2) @ Y(3)) + -0.03599964576765458 * (Y(0) @ Y(1) @ X(2) @ X(3)) + -0.0359996457676545

In [ ]:
print(qubits)

6


In [ ]:
from qiskit_nature.units import DistanceUnit
from qiskit_nature.second_q.drivers import PySCFDriver

driver = PySCFDriver(
    atom="H 0 0 0; H 0 0 0.735",
    basis="sto3g",
    charge=0,
    spin=0,
    unit=DistanceUnit.ANGSTROM,
)

es_problem = driver.run()

INFO:qiskit_nature.second_q.drivers.pyscfd.pyscfdriver:PySCF kernel() converged: True, e(hf): -1.1169989967540035
INFO:qiskit_nature.second_q.operators.symmetric_two_body:Attempting 4-fold to 8-fold symmetric conversion.
INFO:qiskit_nature.second_q.operators.symmetric_two_body:Using PySCF's conversion routine
INFO:qiskit_nature.second_q.drivers.pyscfd.pyscfdriver:HF Electronic dipole moment: [-0.        -0.        -1.3889487]
INFO:qiskit_nature.second_q.drivers.pyscfd.pyscfdriver:Nuclear dipole moment: [0.        0.        1.3889487]
INFO:qiskit_nature.second_q.drivers.pyscfd.pyscfdriver:Total dipole moment: [0. 0. 0.]
